<?php
/**
 * @file
 * Debug UP API calls.
 */

function up_debug_menu() {
  $endpoints = array('bandevents', 'body_events', 'heartrates', 'generic_events', 'goals', 'meals', 'mood', 'moves', 'settings', 'sleeps', 'timezone', 'trends', 'user', 'workouts');

  foreach ($endpoints as $endpoint) {
    $items['admin/config/services/up/debug/' .$endpoint] = array(
      'title' => 'UP: ' . $endpoint,
      'page callback' => 'up_debug_callback',
      'page arguments' => array(5),
      'access arguments' => array('access developer information'),
      'type' => MENU_LOCAL_TASK,
    );
  }

  return $items;
}

function up_debug_callback($item) {

  drupal_set_title(t('UP Debug: @item', array('@item' => $item)));

  $token = up_token_load_by_user($GLOBALS['user']);

  $config = up_api_config($token);
  $up = new \Jawbone\Up($config);

  // Well...
  if ($item == 'user') $item = '';

  try {
    $json = $up->get($item);
  } catch (Exception $e) {
    drupal_set_message(t('@error', array('@error' => (string)$e)), 'error');
  }

  dpm($json, $item);

  return '';
}
